name: Docker Image CI

on:
  push:
    branches: [ "develop", "feature/*", "bugfix/*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image (master)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Miratorg.TimeKeeper.Host/Dockerfile
        push: true
        tags: kluchnikov/time-keeper:0.3.1
